# CI tasks that are required to succeed
# TODO: use only wildcard once it works
status = [
    # "build %",
    "build (16.x, gis)",
    "build (16.x, dashboards/gfbio)",
    "build (16.x, dashboards/data-atlas)",
    "build (16.x, dashboards/nfdi-gdo)",
    "build (16.x, dashboards/ebv-analyzer)",
    "Code Format and Lints",
]

# One approval necessary for bors to work
required_approvals = 1
